from typing import Protocol


class AsyncCachingClient(Protocol):
    async def set(self, key: str, value: str, expiration: int) -> None: ...

    async def get(self, key: str) -> str | None: ...

    async def delete(self, key: str) -> None: ...
