"""make_review_fields_nullable

Revision ID: 5578f68cfbc4
Revises: 29b66343518c
Create Date: 2026-04-26 06:04:22.392867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5578f68cfbc4'
down_revision: Union[str, Sequence[str], None] = '29b66343518c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reviews', 'position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
