"""Add gin indexes for reviews JSONB-fields

Revision ID: 8843f0e69308
Revises: 5578f68cfbc4
Create Date: 2026-04-28 18:01:42.338860

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8843f0e69308"
down_revision: Union[str, Sequence[str], None] = "5578f68cfbc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_reviews_advantages_gin",
        "reviews",
        ["advantages"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_reviews_disadvantages_gin",
        "reviews",
        ["disadvantages"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_reviews_questions_gin",
        "reviews",
        ["questions"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_reviews_questions_gin", table_name="reviews", postgresql_using="gin"
    )
    op.drop_index(
        "ix_reviews_disadvantages_gin", table_name="reviews", postgresql_using="gin"
    )
    op.drop_index(
        "ix_reviews_advantages_gin", table_name="reviews", postgresql_using="gin"
    )
    # ### end Alembic commands ###
