"""Replace reviews JSONB GIN indexes with trigram expression indexes, create review_requests user_id index

Revision ID: daa6549667ff
Revises: 8843f0e69308
Create Date: 2026-04-28 23:03:22.119915

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daa6549667ff"
down_revision: Union[str, Sequence[str], None] = "8843f0e69308"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_review_requests_user_id"), "review_requests", ["user_id"], unique=False
    )
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.drop_index("ix_reviews_advantages_gin", table_name="reviews")
    op.drop_index("ix_reviews_disadvantages_gin", table_name="reviews")
    op.drop_index("ix_reviews_questions_gin", table_name="reviews")
    op.execute(
        "CREATE INDEX ix_reviews_advantages_trgm ON reviews "
        "USING gin ((advantages::text) gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_reviews_disadvantages_trgm ON reviews "
        "USING gin ((disadvantages::text) gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_reviews_questions_trgm ON reviews "
        "USING gin ((questions::text) gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_advantages_trgm", table_name="reviews")
    op.drop_index("ix_reviews_disadvantages_trgm", table_name="reviews")
    op.drop_index("ix_reviews_questions_trgm", table_name="reviews")
    op.create_index(
        "ix_reviews_advantages_gin",
        "reviews",
        ["advantages"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_reviews_disadvantages_gin",
        "reviews",
        ["disadvantages"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_reviews_questions_gin",
        "reviews",
        ["questions"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_review_requests_user_id"), table_name="review_requests")
    # ### end Alembic commands ###
